--Collisions Table
CREATE TABLE collisions ( 
    collision_index                                  VARCHAR(20) PRIMARY KEY, 
    collision_year                                   SMALLINT, 
    collision_ref_no                                 VARCHAR(20), 
    location_easting_osgr                            INTEGER, 
    location_northing_osgr                           INTEGER, 
    longitude                                        NUMERIC(10,5), 
    latitude                                         NUMERIC(10,5), 
    police_force                                     SMALLINT, 
    collision_severity                               SMALLINT, 
    number_of_vehicles                               SMALLINT, 
    number_of_casualties                             SMALLINT, 
    collision_date                                   DATE, 
    day_of_week                                      SMALLINT, 
    collision_time                                   TIME, 
    local_authority_district                         SMALLINT, 
    local_authority_ons_district                     VARCHAR(20), 
    local_authority_highway                          VARCHAR(20), 
    local_authority_highway_current                  VARCHAR(20), 
    first_road_class                                 SMALLINT, 
    first_road_number                                INTEGER, 
    road_type                                        SMALLINT, 
    speed_limit                                      SMALLINT, 
    junction_detail_historic                         SMALLINT, 
    junction_detail                                  SMALLINT, 
    junction_control                                 SMALLINT, 
    second_road_class                                SMALLINT, 
    second_road_number                               INTEGER, 
    pedestrian_crossing_human_control_historic       SMALLINT, 
    pedestrian_crossing_physical_facilities_historic SMALLINT, 
    pedestrian_crossing                              SMALLINT, 
    light_conditions                                 SMALLINT, 
    weather_conditions                               SMALLINT, 
    road_surface_conditions                          SMALLINT, 
    special_conditions_at_site                       SMALLINT, 
    carriageway_hazards_historic                     SMALLINT, 
    carriageway_hazards                              SMALLINT, 
    urban_or_rural_area                              SMALLINT, 
    did_police_officer_attend_scene_of_accident      SMALLINT, 
    trunk_road_flag                                  SMALLINT, 
    lsoa_of_accident_location                        VARCHAR(20), 
    enhanced_severity_collision                      SMALLINT, 
    collision_injury_based                           SMALLINT, 
    collision_adjusted_severity_serious              NUMERIC(8,5), 
    collision_adjusted_severity_slight               NUMERIC(8,5) 

); 


--Vehicles Table

CREATE TABLE vehicles ( 
    collision_index                           VARCHAR(20), 
    collision_year                            SMALLINT, 
    collision_ref_no                          VARCHAR(20), 
    vehicle_reference                         SMALLINT, 
    vehicle_type                              SMALLINT, 
    towing_and_articulation                   SMALLINT, 
    vehicle_manoeuvre_historic                SMALLINT, 
    vehicle_manoeuvre                         SMALLINT, 
    vehicle_direction_from                    SMALLINT, 
    vehicle_direction_to                      SMALLINT, 
    vehicle_location_restricted_lane_historic SMALLINT, 
    vehicle_location_restricted_lane          SMALLINT, 
    junction_location                         SMALLINT, 
    skidding_and_overturning                  SMALLINT, 
    hit_object_in_carriageway                 SMALLINT, 
    vehicle_leaving_carriageway               SMALLINT, 
    hit_object_off_carriageway                SMALLINT, 
    first_point_of_impact                     SMALLINT, 
    vehicle_left_hand_drive                   SMALLINT, 
    journey_purpose_of_driver_historic        SMALLINT, 
    journey_purpose_of_driver                 SMALLINT, 
    sex_of_driver                             SMALLINT, 
    age_of_driver                             SMALLINT, 
    age_band_of_driver                        SMALLINT, 
    engine_capacity_cc                        INTEGER, 
    propulsion_code                           SMALLINT, 
    age_of_vehicle                            SMALLINT, 
    generic_make_model                        VARCHAR(100), 
    driver_imd_decile                         SMALLINT, 
    lsoa_of_driver                            VARCHAR(20), 
    escooter_flag                             SMALLINT, 
    driver_distance_banding                   SMALLINT 

); 

 

-- Casualties Table
CREATE TABLE casualties ( 
    collision_index                        VARCHAR(20), 
    collision_year                         SMALLINT, 
    collision_ref_no                       VARCHAR(20), 
    vehicle_reference                      SMALLINT, 
    casualty_reference                     SMALLINT, 
    casualty_class                         SMALLINT, 
    sex_of_casualty                        SMALLINT, 
    age_of_casualty                        SMALLINT, 
    age_band_of_casualty                   SMALLINT, 
    casualty_severity                      SMALLINT, 
    pedestrian_location                    SMALLINT, 
    pedestrian_movement                    SMALLINT, 
    car_passenger                          SMALLINT, 
    bus_or_coach_passenger                 SMALLINT, 
    pedestrian_road_maintenance_worker     SMALLINT, 
    casualty_type                          SMALLINT, 
    casualty_imd_decile                    SMALLINT, 
    lsoa_of_casualty                       VARCHAR(20), 
    enhanced_casualty_severity             SMALLINT, 
    casualty_injury_based                  SMALLINT, 
    casualty_adjusted_severity_serious     NUMERIC(8,5), 
    casualty_adjusted_severity_slight      NUMERIC(8,5), 
    casualty_distance_banding              SMALLINT 

); 